<footer>
	<div class="footerIn">
		<ul>
			<a href="http://www.indianpac.com" target="_blank"><li>I-PAC</li></a><!-- <li>Download brochure</li> --><a href="<?php echo base_url()?>assets/images/NAF-Concept-Note.pdf" target="_blank"><li id="about">About NAF</li></a><li class="openPopup" id="faq">FAQs</li><li class="openPopup" id="privacy">Privacy Policy</li><li class="openPopup" id="terms">Terms & Conditions</li>
		</ul>
		<div class="copyright">National Agenda Forum 2019</div>
	</div>
</footer>
<div class="popup otpPopup" >
    <div class="popupIn">
        <div class="table_cell">
            <div class="popupData">
                 <div class="closePopup">Cancel</div> 
                <h5>Enter OTP</h5>
                <form name="otp_submit" id="otp_submit" autocomplete="off">
                    <input type="number" name="user_otp" id="user_otp" value=""><input class="btn" type="submit" value="Submit">
                    <p class="resendOtp"><span>Resend OTP</span></p>
                    <div class="error">
                        <span id="user_otp_error"></span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="popup popUpOverlayClose infoDataPopup">
    <div class="popupIn">
        <div class="table_cell">
            <div class="popupData infoPopupData">
                <div class="closePopup">Close</div>
                <div class="infoIn termsInfo">
	                <h5>TERMS AND CONDITIONS FOR ENGAGEMENT AS PART TIME ASSOCIATES</h5>
	                <p>The following terms and conditions contained herein (“Terms and Conditions”) shall govern your engagement as a Part Time Associate (“PTA”/”You”) with Indian PAC Consulting Pvt. Ltd. ("I-PAC"), a private limited company incorporated under the provisions of the Companies Act, 1956 and an existing company under the provisions of the Companies Act, 2013 having its registered office at Flat No-4A, Khushi Vila, East Boring Canel Road, Patna-800001.</p>
	                <h5 class="termHead">TERMS AND CONDITIONS</h5>
	                <ul class="numberBullets">
	                	<li>Your usage of the website- <a href="http://www.indianpac.com" target="_blank">http://www.indianpac.com/</a> (including all sub-pages thereof) shall be governed by I-PAC’s Fair Usage Policy and all applicable laws.</li>
	                	<li>By clicking on the “I Agree” button provided on PTA registration form you undertake that you have perused the Terms and Conditions and the Fair Usage Policy contained herein, in its entirety and agree to comply with the same without any coercion, duress or misrepresentation by I-PAC, any of its employees or any other third party.</li>
	                 	<li>You shall grant I-PAC the absolute right and authority to use your Personal Information (as defined under applicable laws) and all other information submitted by you during the course of your engagement as a PTA for communication, promotion or engagement in any manner it may deem fit, at its sole discretion. However, I-PAC warrants that your Personal Information will not be shared with any external third party without your consent.</li>
	                	<li>Your engagement as a PTA is strictly on a temporary and voluntary basis only and does not create an Employer-Employee relationship between you and I-PAC. Therefore, you shall not have any claims for remuneration, reimbursement or any other benefits available to an employee of I-PAC.</li>
	                	<li>There is no obligation on I-PAC to absorb you as an employee or offer an internship with I-PAC post the expiry or termination of your engagement, whichever is earlier.</li>
	                	<li>All the information, data and content received by you from I-PAC or any of its employees (whether in written or verbal form), is the proprietary information of I-PAC and you shall not disclose or divulge such information to any third party except with the prior written authorization of I-PAC.</li>
	                	<li>You hereby undertake that you will own or procure (at your own cost) the intellectual property rights to all the content created or provided by you during the course of your engagement with I-PAC. Further, you shall provide a royalty-free worldwide license to I-PAC to use the content generated by you in a manner it deems fit, at its sole discretion.</li>
	                	<li>You hereby indemnify to the fullest extent the Company, its officers, directors, employees, agents from and against any and all liabilities, costs, demands, causes of action, damages and expenses (including reasonable attorney’s fees) resulting from or alleged to result from the violation of these Terms and Conditions.</li>
	                	<li>Upon violation of any of these Terms by you, I-PAC reserves the right to take appropriate actions to prevent/control such violation.</li>
	                	<li>In no event shall I-PAC nor any of its officers, directors and employees, be liable to you for anything arising out of or in any way connected with your use of this Website, whether such liability is under contract, tort or otherwise, and I-PAC, including its officers, directors and employees shall not be liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.</li>
	                	<li>If any provision of these Terms and Conditions is found to be unenforceable or invalid under any applicable law, such unenforceability or invalidity shall not render these Terms and Conditions unenforceable or invalid as a whole, and such provisions shall be deleted without affecting the remaining provisions herein.</li>
	                	<li>I-PAC may, in its sole discretion, amend or revise these Terms and Conditions from time to time with or without any notification. Your consent shall be deemed to be provided to such revised terms and conditions in the absence of any specific written objection or query from you to IPAC.</li>
	                	<li>These Terms, including any legal notices and disclaimers contained on this Website, constitute the entire agreement between Company and you in relation to your use of this Website, and supersede all prior agreements and understandings with respect to the same.</li>
						<li>You shall not at any time, in any way publicly disparage, call into disrepute, defame, slander or otherwise criticize I-PAC or any of its clients.</li>
						<li>I-PAC reserves the right to terminate your engagement immediately at any point without any notice, at its sole discretion on grounds including but not limited to gross negligence, misconduct, fraud, misrepresentation, vandalism, harassment or any other grounds as it may deem fit.</li>
						<li>These Terms and Conditions shall be governed by the laws of India and any dispute arising from or in relation to this shall be subject to the exclusive jurisdiction of the courts of Hyderabad, Telangana.</li>
	                </ul>
	            </div>
                <div class="infoIn aboutInfo">
	                <h5>About NAF</h5>
	                <p>Taking the spirit forward, 73 years later, I-PAC together with its associates and volunteers attempts to bring together millions of fellow citizens through the <b>National Agenda Forum (NAF)</b>, a pan-India initiative to <b>resurrect the conversation</b> arounf Gandhi's 18-point Contructive Programme and use it to <b>re-imagin and co-create India's priority</b> to formulate an actionable agenda for the present.</p>
	                <p>Inspired by Gandhi's Contructive Programme for a new India.</p>
	            </div>
	            <div class="infoIn faqInfo">
	            	<h5>NAF Frequently Asked Questions</h5>
	            	<div class="qtnOut">
		            	<p class="qtnNo">1. </p>
		            	<h6>What is NAF?</h6>
		            	<p>The National Agenda Forum provides an unprecedented platform for educated youth and professionals of the country to come together, give voice to the masses, and set the priorities for India in General Elections 2019.</p>
		            	<p>On 29 th June 2018, 11000 Students from 1525 Colleges across 560 Districts of India are coming together to launch the biggest youth movement of the millennium.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">2. </p>
		            	<h6>Why NAF?</h6>
		            	<p>Through NAF, I-PAC aims to provide educated youth and young professionals a platform to not only set a positive agenda for India, but also choose the Leader who can implement it. I-PAC takes special pride in pioneering a bridge between youth & politics.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">3. </p>
		            	<h6>Who is a NAF Fellow?</h6>
		            	<p>NAF Fellows will be the agents to become the voice of the masses, engage the masses to choose leaders & set the agenda for the Government. To become NAF Fellow, register on <a href="http://www.indianpac.com/naf/" target="_blank">www.indianpac.com/naf</a></p>
		            	<p>The NAF Fellows:</p>
		            	<ul>
		            		<li>Choose the Leader</li>
		            		<li>Engage the Nation</li>
		            		<li>Set the Agenda</li>
		            	</ul>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">4. </p>
		            	<h6>What are the incentives to be a NAF Fellow?</h6>
		            	<p><b>Incentives</b></p>
		            	<ul>
		            		<li>Choose Leader & Set Agenda
		            			<ul>
		            				<li>Lead the initiative to choose the right leader & set the people’s agenda for the chosen leader in General Elections 2019</li>
		            			</ul>
		            		</li>
		            		<li>Leader Engagement
		            			<ul>
		            				<li>Opportunity to meaningfully engage with the chosen National Leadership</li>
		            			</ul>
		            		</li>
		            		<li>Become a PTA with I-PAC
		            			<ul>
		            				<li>Get a chance to become a part of the core team of I-PAC as a Part Time Associate (PTA)</li>
		            			</ul>
		            		</li>
		            		<li>NAF Certificate
		            			<ul>
		            				<li>Certificates of Achievement for all NAF Fellows</li>
		            			</ul>
		            		</li>
		            	</ul>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">5. </p>
		            	<h6>What will be done in the National Agenda Forum?</h6>
		            	<p><b>NAF Milestones & Process</b></p>
		            	<ul>
		            		<li>29 th June 2018 – NAF Launch</li>
		            		<li>20 th July 2018 – NAF Fellows Choose Leader</li>
		            		<li>Before 15 th Aug 2018 – Fellows meet the chosen Leader and crowdsourcing of Agenda starts</li>
		            		<li>2 nd October 2018 – People’s Agenda is revealed</li>
		            	</ul>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">6. </p>
		            	<h6>What is I-PAC?</h6>
		            	<p>Indian Political Action Committee (I-PAC) is a platform of choice for educated youth and young professionals who want to meaningfully contribute to the polity of India without necessarily being part of a political party.</p>
		            	<p>I-PAC started as Citizens for Accountable Governance (CAG) in 2013, when for the first time in the history of Indian Politics, a group of young professionals from world renowned academic and professional institutions, got together to bring socio-political change by involving the youth of the country in furthering the cause of accountable governance and help set the agenda of the Government.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">7. </p>
		            	<h6>What does I-PAC do?</h6>
		            	<p>I-PAC endeavors to support the election of visionary, progressive and inclusive leaders to public offices. The intent is to understand and captures people’s aspirations as well as directly make them a part of the Governments’ agenda. This group redefined the way of election campaigning in India through state of the art campaigns.</p>
		            	<p>I-PAC has worked with Mr. Narendra Modi in 2014 General Elections, Mr. Nitish Kumar in Bihar 2015, Captain Amarinder Singh in Punjab 2017, and Mr. Rahul Gandhi in Uttar Pradesh 2017. The group is currently working with Mr. Y S Jagan Mohan Reddy for Andhra Pradesh 2019.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">8. </p>
		            	<h6>Is I-PAC affiliated to any particular political party?</h6>
		            	<p>No, it has worked with different parties across the political spectrum. In the past we have worked with BJP - 2014, Mahagatbandhan (JDU, INC, RJD) - 2015, INC (UP, Punjab) - 2017 and YSRCP (AP) - 2019.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">9. </p>
		            	<h6>How does I-PAC choose the leaders it wants to work with?</h6>
		            	<p>I-PAC is committed to work with progressive and visionary leaders. We choose leaders who are willing to consider and discuss people driven agendas and also possess the receptivity to consider ideas upon which credible manifestos can be drafted.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">10. </p>
		            	<h6>What ideology does I-PAC confirm to?</h6>
		            	<p>At I-PAC we believe that performance and delivery should be prioritized over any ideology in terms of judging a Leader/Government’s ability or performance.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">11. </p>
		            	<h6>I have 5 friends who want to be NAF Fellow. How do they join NAF?</h6>
		            	<p>On 29 th Jun, 2018 NAF will be launched. People interested can go to the site <a href="http://www.indianpac.com/naf/" target="_blank">www.indianpac.com/naf</a>. They have to first vote their choice for the leader who can deliver a people’s agenda in India and can register as NAF subsequently</p>
		            </div>
		            
		            <div class="qtnOut">
		            	<p class="qtnNo">12. </p>
		            	<h6>What is PTA?</h6>
		            	<p>PTAs are Part Time Associates of I-PAC who have expressed an interest in helping I-PAC build and strengthen the National Agenda Forum and for becoming a core part of NAF. PTAs become a point of contact in their college and help us launch NAF on campus on 29 th June.</p>
		            	<p>As a PTA, you get to be,</p>
		            	<ul class="romanList">
		            		<li>An active member in shaping the key political discourse in India</li>
		            		<li>A partner in I-PAC’s decision making</li>
		            		<li>Considered in internship and job opportunities at I-PAC</li>
		            		<li>Involved in a forum of like-minded people</li>
		            		<li>Mentored on On-ground Leadership by I-PAC’s professionals</li>
		            		<li>Connected with national and state-level political leadership</li>
		            	</ul>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">13.  </p>
		            	<h6>How is a PTA different from NAF Fellow?</h6>
		            	<p>PTA is a part time associate with I-PAC who will help launch and engage the National Agenda Forum. The PTAs will be associated with I-PAC in the long term and shall be directly in contact with the I-PAC members. PTAs will enroll individuals in NAF who will be known as a NAF Fellow. NAF Fellows will be the agents to become the voice of the masses, engage the masses to choose leaders & set the agenda for the Government.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">14. </p>
		            	<h6>How can I become a PTA?</h6>
		            	<p>To become a PTA, as a first step, you need to register at <a href="http://www.indianpac.com/naf/" target="_blank">www.indianpac.com/pta</a></p>
		            	<p>To confirm your registration, you need to reach out to 10 individuals in your network, inform them about NAF and have them join the forum as NAF Fellows. Your reference code will be used by the NAF Fellows at the time of their registration. Communication from Team I-PAC will follow regularly thereafter.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">15. </p>
		            	<h6>Would all the work of PTAs be only online/telephonic?</h6>
		            	<p>Regularly I-PAC will send detailed engagement plans with respect to both digital and on ground activities. It is up to the PTAs availability and discretion all the activities they would like to be involved in. I-PAC would happily welcome maximum participation.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">16. </p>
		            	<h6>Is this a paid job?</h6>
		            	<p>No. This role does not include paid remuneration of any kind.</p>
		            </div>
		            <div class="qtnOut">
		            	<p class="qtnNo">17. </p>
		            	<h6>What are future opportunities for a PTA?</h6>
		            	<p>In future, PTAs can be considered on priority for internship and job opportunities at I-PAC</p>
		            </div>
	            </div>

	            <div class="infoIn privacyInfo">
	            	<h5>NAF Privacy Policy</h5>
	            	<p>Your privacy is important to us and this Privacy Policy shall govern your engagement as a Part Time Associate (“PTA”/”You”) with Indian PAC Consulting Pvt. Ltd. (&quot;I-PAC, &quot;us&quot;, &quot;we&quot;) and your usage of the website http://www.indianpac.com/ (hereinafter referred to as the “website”).</p>
					<p>Your privacy is important to us and this Privacy Policy shall govern your engagement as a Part Time Associate (“PTA”/”You”) with Indian PAC Consulting Pvt. Ltd. (&quot;I-PAC, &quot;us&quot;, &quot;we&quot;) and your usage of the website http://www.indianpac.com/ (hereinafter referred to as the “website”).</p>
	            	<div class="qtnOut">
		            	<!-- <p class="qtnNo">1. </p> -->
		            	<h6>Personal information collection:</h6>
		            	<p>Personal Information means and includes all information that can be linked to a specific individual or to identify any individual, such as name, address, mailing address, telephone number, e-mail address, Aadhar number, constituency, voter details, information about the constituency, and any and all details that may be requested while any user visits or uses the website.</p>
						<p>We may collect and use the following kinds of personal information that you provide using for the purpose of registering with the website:</p>
						<ul>
							<li>Name</li>
							<li>Address</li>
							<li>Phone number</li>
							<li>Email address</li>
							<li>Date of birth</li>
							<li>College information</li>
							<li>vote preference</li>
							<li>Other data that could directly or indirectly identify you.</li>
						</ul>
		            </div>
		            <div class="qtnOut">
		            	<!-- <p class="qtnNo">2. </p> -->
		            	<h6>Using personal information:</h6>
		            	<p>We may use your personal information:</p>
		            	<ul>
		            		<li>for communication through Email, SMS, Calls, IVR, WhatsApp and social media platforms.</li>
		            		<li>to display your information (name, photo, college, state and district) on our website and other I-PAC`s social media properties.</li>
		            	</ul>
		            	<p>This is also to inform you that your information will never be shared with any third party and your vote preference will never be shown to public. Polling data will be used at overall level to show the final results.</p>
		            </div>
		            <div class="qtnOut">
		            	<!-- <p class="qtnNo">3. </p> -->
		            	<h6>Securing of your data:</h6>
		            	<p>We will store all the personal information provided by you on our secured servers and will take reasonable technical and organizational precautions to prevent the loss, misuse or alteration of your personal information.</p>
		            </div>
		            <div class="qtnOut">
		            	<!-- <p class="qtnNo">4. </p> -->
		            	<h6>Compliance with legal, regulatory, and law enforcement requests:</h6>
		            	<p>We cooperate with law enforcement and government officials and private parties to comply with the law. We will, in our sole discretion, disclose any information about you to such parties as necessary to respond to claims and legal processes, to protect our property and rights or the property and rights of a third party, to protect the safety of the public or an individual, or to prevent or stop illegal or unethical activity.</p>
		            	<p>If we are legally permitted to do so, we will take reasonable steps to notify you in the event we are required to provide your information to third parties as part of a legal process.</p>
		            </div>
		            <div class="qtnOut">
		            	<!-- <p class="qtnNo">4. </p> -->
		            	<h6>Updating this statement:</h6>
		            	<p>We may update this privacy policy by posting a new version on the website and we encourage you to review our Privacy Policy, occasionally to ensure you are familiar with any changes.</p>
		            </div>
	            </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo base_url()?>assets/js/jquery.min.js"></script>
<script src="<?php echo base_url()?>assets/js/slick.js" ></script>
<script src="https://connect.facebook.net/en_US/all.js"></script>
<script src="<?php echo base_url()?>assets/js/main.js" ></script>